### ISSUE TITLE
Pending Issues or Features

### ISSUE THREAD

**Issue by Chibuikekenneth** [carbonplayer/carbon#2]
Are there any current Issues or things to add @spatocode ?

**Comment by spatocode** [comment]
Hi @Chibuikekenneth . There are probably lots of issues. I've filed some tickets for some known issues. Hopefully we could handle better.

**Comment by spatocode** [comment]
I'll close this now in favour of #4 #5 #6

**Comment by Chibuikekenneth** [comment]
Awesome !!! Thanks @spatocode
